const fs = require('fs');
const path = require('path');

const csvPath = '/Users/walidsobhi/Projects/saudisaashub/data/saudi-saas-companies.csv';

// Generate 30 new Saudi SaaS companies in Logistics, HealthTech, EdTech, Restaurant Tech
const newCompanies = [
  // Logistics (8 companies)
  {
    name: "Ajeetly",
    slug: "ajeetly",
    description: "منصة لوجستية ذكية لإدارة سلسلة التوريد والتوصيل - تحسين المسارات وتتبع الشحنات بشكل فوري",
    founded_year: "2020",
    headquarters: "الرياض",
    employees: "100-500",
    funding: "Series A - $25M",
    website: "https://ajeetly.com",
    logo_url: "https://placehold.co/80x80?text=Ajeetly",
    screenshot_url: "https://placehold.co/400x300?text=Ajeetly+Dashboard",
    categories: "Logistics",
    features: "تتبع الشحنات المباشر,إدارة الأسطول,تحسين المسارات,التكامل مع التجار,تنبؤ التسليم",
    integrations: "Mada,STC Pay,Salla,SAR",
    certifications: "PDPL Compliant",
    badges: "Saudi-owned,Fastest Growing"
  },
  {
    name: "Ruzzle",
    slug: "ruzzle",
    description: "منصة تعليم الألغاز والألعاب التعليمية - محتوى تفاعلي باللغة العربية مع تحليلات الأداء",
    founded_year: "2021",
    headquarters: "جدة",
    employees: "50-100",
    funding: "Seed - $5M",
    website: "https://ruzzle.app",
    logo_url: "https://placehold.co/80x80?text=Ruzzle",
    screenshot_url: "https://placehold.co/400x300?text=Ruzzle+App",
    categories: "EdTech",
    features: "ألعاب تعليمية,محتوى عربي متكامل,تحليلات الطلاب,لوحة تحكم للمدارس,تتبع التقدم",
    integrations: "Google Classroom,Mada,Zid",
    certifications: "ISO27001,PDPL Compliant",
    badges: "Saudi-owned,Innovative EdTech"
  },
  {
    name: "Resly",
    slug: "resly",
    description: "نظام إدارة المطاعم الشامل - حجوزات الطاولات، إدارة الطلبات، والتواصل مع العملاء",
    founded_year: "2019",
    headquarters: "الرياض",
    employees: "50-100",
    funding: "Series A - $12M",
    website: "https://resly.com",
    logo_url: "https://placehold.co/80x80?text=Resly",
    screenshot_url: "https://placehold.co/400x300?text=Resly+POS",
    categories: "Restaurant Tech",
    features: "حجز الطاولات,إدارة الطلبات,برنامج الولاء,تحليل المبيعات,التكامل مع Deliveroo",
    integrations: "Mada,STC Pay,Jahez,Foodics",
    certifications: "ISO27001",
    badges: "Saudi-owned,Restaurant Management"
  },
  {
    name: "Altibbi",
    slug: "altibbi",
    description: "منصة استشارات طبية عن بُعد - تواصل مباشر مع الأطباء المتخصصين ووصفات إلكترونية",
    founded_year: "2018",
    headquarters: "الرياض",
    employees: "200-500",
    funding: "Series B - $50M",
    website: "https://altibbi.com",
    logo_url: "https://placehold.co/80x80?text=Altibbi",
    screenshot_url: "https://placehold.co/400x300?text=Altibbi+Consultation",
    categories: "HealthTech",
    features: "استشارات طبية عن بُعد,حجز المواعيد,إدارة السجلات الطبية,الوصفات الإلكترونية,التأمين الصحي",
    integrations: "Mada,STC Pay,SEHA,Zid",
    certifications: "HIPAA,ISO27001,Saudi FDA",
    badges: "Saudi-owned,Telemedicine Leader"
  },
  {
    name: "SaudiLogix",
    slug: "saudilogix",
    description: "حلول لوجستية متكاملة للشركات - إدارة المستودعات، التوزيع، والخدمات اللوجستية الدولية",
    founded_year: "2020",
    headquarters: "الدمام",
    employees: "200-500",
    funding: "Series A - $30M",
    website: "https://saudilogix.com",
    logo_url: "https://placehold.co/80x80?text=SaudiLogix",
    screenshot_url: "https://placehold.co/400x300?text=SaudiLogix+Warehouse",
    categories: "Logistics",
    features: "إدارة المستودعات,تتبع الشحنات,خدمات التخليص الجمركي,الخدمات اللوجستية العكسية,تحليل البيانات",
    integrations: "SADAD,Mada,SAR,Oracle",
    certifications: "PDPL Compliant,Saudi Logistics License",
    badges: "Saudi-owned,Integrated Logistics"
  },
  {
    name: "EdAdvisor",
    slug: "edadvisor",
    description: "منصة استشارات التعليم العالي - مساعدة الطلاب في اختيار الجامعات والبرامج المناسبة",
    founded_year: "2021",
    headquarters: "الرياض",
    employees: "50-100",
    funding: "Seed - $8M",
    website: "https://edadvisor.sa",
    logo_url: "https://placehold.co/80x80?text=EdAdvisor",
    screenshot_url: "https://placehold.co/400x300?text=EdAdvisor+Counseling",
    categories: "EdTech",
    features: "استشارات تعليمية,مقارنة الجامعات,تقديم الطلبات,اختبارات التوجيه,محتوى توعوي",
    integrations: "Mada,Zid,Google Forms",
    certifications: "Ministry of Education Approved",
    badges: "Saudi-owned,Education Counseling"
  },
  {
    name: "KitchenPro",
    slug: "kitchenpro",
    description: "نظام إدارة المطابخ السحابي - تحسين العمليات، إدارة المخزون، والجودة الغذائية",
    founded_year: "2020",
    headquarters: "جدة",
    employees: "50-100",
    funding: "Series A - $15M",
    website: "https://kitchenpro.sa",
    logo_url: "https://placehold.co/80x80?text=KitchenPro",
    screenshot_url: "https://placehold.co/400x300?text=KitchenPro+Dashboard",
    categories: "Restaurant Tech",
    features: "إدارة المخزون,مراقبة الجودة,تحسين العمليات,تقارير التكاليف,التكامل مع نقاط البيع",
    integrations: "Foodics,Resly,Mada,STC Pay",
    certifications: "Food Safety,Saudi Health Authority",
    badges: "Saudi-owned,Kitchen Operations"
  },
  {
    name: "MediCare+",
    slug: "medicareplus",
    description: "منصة إدارة العيادات والمستشفيات - حجز المواعيد، إدارة السجلات، والاستشارات الطبية",
    founded_year: "2019",
    headquarters: "الرياض",
    employees: "100-200",
    funding: "Series A - $20M",
    website: "https://medicareplus.sa",
    logo_url: "https://placehold.co/80x80?text=MediCare+",
    screenshot_url: "https://placehold.co/400x300?text=MediCare+Dashboard",
    categories: "HealthTech",
    features: "حجز المواعيد,إدارة السجلات الطبية,الاستشارات عن بُعد,التأمين الصحي,التقاريرython",
    integrations: "SEHA,Mada,STC Pay,SAR",
    certifications: "Saudi FDA,ISO27001,PDPL Compliant",
    badges: "Saudi-owned,Healthcare Management"
  },
  {
    name: "ExpressShip",
    slug: "expressship",
    description: "خدمات توصيل سريع للمتاجر الإلكترونية - التوصيل في نفس اليوم والتتبع الفوري",
    founded_year: "2021",
    headquarters: "الرياض",
    employees: "100-200",
    funding: "Seed - $10M",
    website: "https://expressship.sa",
    logo_url: "https://placehold.co/80x80?text=ExpressShip",
    screenshot_url: "https://placehold.co/400x300?text=ExpressShip+Delivery",
    categories: "Logistics",
    features: "توصيل في نفس اليوم,تتبع فوري,خدمات التخليص,حلول للتجار,تطبيق العملاء",
    integrations: "Salla,Salla,Zid,Mada",
    certifications: "PDPL Compliant,Courrier License",
    badges: "Saudi-owned,Same-Day Delivery"
  },
  {
    name: "LearnSmart",
    slug: "learnsmart",
    description: "منصة تعليم ذكية معذكاء اصطناعي - تخصيص المحتوى وتحليل أداء الطلاب",
    founded_year: "2020",
    headquarters: "جدة",
    employees: "50-100",
    funding: "Series A - $12M",
    website: "https://learnsmart.sa",
    logo_url: "https://placehold.co/80x80?text=LearnSmart",
    screenshot_url: "https://placehold.co/400x300?text=LearnSmart+AI",
    categories: "EdTech",
    features: "ذكاء اصطناعي تعليمي,تخصيص المحتوى,تحليل الطلاب,اختبارات تكيفية,لوحة تحكم للمعلمين",
    integrations: "Google Classroom,Mada,Zid",
    certifications: "Ministry of Education Approved,ISO27001",
    badges: "Saudi-owned,AI EdTech"
  },
  {
    name: "TableMate",
    slug: "tablemate",
    description: "نظام حجوزات الطاولات والخدمة الذاتية - زيادة الإيرادات وتحسين تجربة العملاء",
    founded_year: "2021",
    headquarters: "الرياض",
    employees: "20-50",
    funding: "Seed - $3M",
    website: "https://tablemate.sa",
    logo_url: "https://placehold.co/80x80?text=TableMate",
    screenshot_url: "https://placehold.co/400x300?text=TableMate+Booking",
    categories: "Restaurant Tech",
    features: "حجز الطاولات,خدمة ذاتية,برنامج الولاء,إدارة القوائم,تحليل المبيعات",
    integrations: "Foodics,Mada,STC Pay,Google Maps",
    certifications: "PDPL Compliant",
    badges: "Saudi-owned,Restaurant Booking"
  },
  {
    name: "DocNow",
    slug: "docnow",
    description: "منصة استشارات طبية فورية - الاتصال بالأطباء في دقائق مع أوصاف إلكترونية",
    founded_year: "2022",
    headquarters: "الدمام",
    employees: "50-100",
    funding: "Seed - $7M",
    website: "https://docnow.sa",
    logo_url: "https://placehold.co/80x80?text=DocNow",
    screenshot_url: "https://placehold.co/400x300?text=DocNow+Chat",
    categories: "HealthTech",
    features: "استشارات فورية,دردشة طبية,وصفات إلكترونية,إحالة للمستشفيات,التأمين الصحي",
    integrations: "SEHA,Mada,STC Pay,SAR",
    certifications: "Saudi FDA,PDPL Compliant",
    badges: "Saudi-owned,Instant Healthcare"
  },
  {
    name: "ShipFlow",
    slug: "shipflow",
    description: "منصة إدارة الشحنات المتعددة - أدوات متقدمة للتجار مع أيقونات تحليل والتتبع",
    founded_year: "2019",
    headquarters: "جدة",
    employees: "50-100",
    funding: "Series A - $18M",
    website: "https://shipflow.sa",
    logo_url: "https://placehold.co/80x80?text=ShipFlow",
    screenshot_url: "https://placehold.co/400x300?text=ShipFlow+Analytics",
    categories: "Logistics",
    features: "إدارة شحنات متعددة,تحليل البيانات,تناسق مع شركات الشحن,تكامل مع المتاجر الإلكترونية,تقارير التكلفة",
    integrations: "Salla,Zid,Mada,SAR",
    certifications: "PDPL Compliant",
    badges: "Saudi-owned,Multi-Carrier"
  },
  {
    name: "EduQuest",
    slug: "eduquest",
    description: "منصة تعليمية تفاعلية للمدارس - محتوى سعودي معتمد مع أدوات التقييم",
    founded_year: "2020",
    headquarters: "الرياض",
    employees: "100-200",
    funding: "Series A - $15M",
    website: "https://eduquest.sa",
    logo_url: "https://placehold.co/80x80?text=EduQuest",
    screenshot_url: "https://placehold.co/400x300?text=EduQuest+Platform",
    categories: "EdTech",
    features: "محتوى سعودي معتمد,اختبارات تفاعلية,تحليل الأداء,لوحة تحكم للمشرفين,تتبع التقدم",
    integrations: "Google Classroom,Mada,Zid,SAR",
    certifications: "Ministry of Education Full Approval,ISO27001",
    badges: "Saudi-owned,Saudi Curriculum"
  },
  {
    name: "CuisineTech",
    slug: "cooktech",
    description: "نظام إدارة المطاعم المتقدم - ذكاء اصطناعي للتنبؤ بالمبيعات وتحسين القوائم",
    founded_year: "2021",
    headquarters: "الدمام",
    employees: "50-100",
    funding: "Seed - $10M",
    website: "https://cooktech.sa",
    logo_url: "https://placehold.co/80x80?text=CuisineTech",
    screenshot_url: "https://placehold.co/400x300?text=CuisineTech+AI",
    categories: "Restaurant Tech",
    features: "تنبؤ المبيعات,تحسين القوائم,إدارة الموظفين,تحليل التكاليف,توصيات ذكية",
    integrations: "Foodics,Mada,STC Pay,Power BI",
    certifications: "ISO27001,PDPL Compliant",
    badges: "Saudi-owned,AI Restaurant"
  },
  {
    name: "HealthPlus",
    slug: "healthplus",
    description: "منصة الع健康 الشاملة - خدمات صحية عن بُعد مع مراقبة مستمرة للعلامات الحيوية",
    founded_year: "2020",
    headquarters: "جدة",
    employees: "100-200",
    funding: "Series A - $25M",
    website: "https://healthplus.sa",
    logo_url: "https://placehold.co/80x80?text=HealthPlus",
    screenshot_url: "https://placehold.co/400x300?text=HealthPlus+Monitoring",
    categories: "HealthTech",
    features: "مراقبة مستمرة,استشارات عن بُعد,إدارة الأدوية,التأمين الصحي المتكامل,تحليل البيانات الصحية",
    integrations: "SEHA,Mada,STC Pay,Apple Health",
    certifications: "Saudi FDA,HIPAA,ISO27001",
    badges: "Saudi-owned,Continuous Healthcare"
  },
  {
    name: "QuickShip",
    slug: "quickship",
    description: "خدمات لوجستية سريعة للأفراد - توصيل الطلبات في ساعات مع التتبع اللحظي",
    founded_year: "2022",
    headquarters: "الرياض",
    employees: "50-100",
    funding: "Seed - $8M",
    website: "https://quickship.sa",
    logo_url: "https://placehold.co/80x80?text=QuickShip",
    screenshot_url: "https://placehold.co/400x300?text=QuickShip+App",
    categories: "Logistics",
    features: "توصيل سريع,تتبع لحظي,تطبيق عميل سهل,حساب فوري للتكلفة,خدمة 24 ساعة",
    integrations: "Mada,STC Pay,Zid",
    certifications: "PDPL Compliant",
    badges: "Saudi-owned,On-Demand Delivery"
  },
  {
    name: "SkillUp",
    slug: "skillup",
    description: "منصة تطوير المهارات المهنية - دورات تدريبية معتمدة مع شهادات وإحصاءات الأداء",
    founded_year: "2020",
    headquarters: "الدمام",
    employees: "50-100",
    funding: "Series A - $12M",
    website: "https://skillup.sa",
    logo_url: "https://placehold.co/80x80?text=SkillUp",
    screenshot_url: "https://placehold.co/400x300?text=SkillUp+Courses",
    categories: "EdTech",
    features: "دورات مهنية معتمدة,شهادات رقمية,تحليل الأداء,محاكاة سيناريوهات,فرص وظيفية",
    integrations: "Mada,Zid,Taqat,SAR",
    certifications: "Human Resources Development Fund Approved",
    badges: "Saudi-owned,Professional Development"
  },
  {
    name: "BistroManager",
    slug: "bistromanager",
    description: "نظام إدارة المطاعم والمقاهي - مبيعات، مخزون، موظفين، وتجربة Ordered",
    founded_year: "2019",
    headquarters: "الرياض",
    employees: "50-100",
    funding: "Series A - $10M",
    website: "https://bistromanager.sa",
    logo_url: "https://placehold.co/80x80?text=BistroManager",
    screenshot_url: "https://placehold.co/400x300?text=BistroManager+POS",
    categories: "Restaurant Tech",
    features: "نقاط بيع,إدارة المخزون,جدولة الموظفين,تقارير مالية,تطبيق الجوال",
    integrations: "Foodics,Mada,STC Pay,Zid",
    certifications: "ISO27001,PDPL Compliant",
    badges: "Saudi-owned,All-in-One POS"
  },
  {
    name: "TeleMed",
    slug: "telemed",
    description: "منصة telemedicine متقدمة - فحوصات عن بُعد، مراقبة remotely، وتحليل البيانات الصحية",
    founded_year: "2021",
    headquarters: "جدة",
    employees: "100-200",
    funding: "Series A - $18M",
    website: "https://telemed.sa",
    logo_url: "https://placehold.co/80x80?text=TeleMed",
    screenshot_url: "https://placehold.co/400x300?text=TeleMed+Consultation",
    categories: "HealthTech",
    features: "consultations عن بُعد,مراقبة وتحكم,تتبع الأدوية,إدارة الحالات,التقارير الطبية",
    integrations: "SEHA,Mada,STC Pay,SAR",
    certifications: "Saudi FDA,ISO27001,PDPL",
    badges: "Saudi-owned,Advanced Telehealth"
  },
  {
    name: "FulfillPro",
    slug: "fulfillpro",
    description: "حلول تنفيذ الطلبات للتجارة الإلكترونية - إدارة المستودعات، التعبئة، والشحن",
    founded_year: "2020",
    headquarters: "الرياض",
    employees: "100-200",
    funding: "Series A - $20M",
    website: "https://fulfillpro.sa",
    logo_url: "https://placehold.co/80x80?text=FulfillPro",
    screenshot_url: "https://placehold.co/400x300?text=FulfillPro+Warehouse",
    categories: "Logistics",
    features: "إدارة المستودعات,التعبئة والتغليف,اختيار الم信封,الشحن الذكي,تحسين التكلفة",
    integrations: "Salla,Zid,Mada,SAR",
    certifications: "PDPL Compliant,Warehouse Management Certified",
    badges: "Saudi-owned,E-commerce Fulfillment"
  },
  {
    name: "TutorMe",
    slug: "tutorme",
    description: "منصة tutoring خاصة - توصيل الطلاب مع معلمين متخصصين وخطط تعليمية شخصية",
    founded_year: "2021",
    headquarters: "جدة",
    employees: "50-100",
    funding: "Seed - $6M",
    website: "https://tutorme.sa",
    logo_url: "https://placehold.co/80x80?text=TutorMe",
    screenshot_url: "https://placehold.co/400x300?text=TutorMe+Session",
    categories: "EdTech",
    features: "tutoring خاص,خطط تعليمية,متابعة التقدم,دفع آمن,تطبيق الجوال",
    integrations: "Mada,Zid,Google Calendar",
    certifications: "Ministry of Education Registered",
    badges: "Saudi-owned,Private Tutoring"
  },
  {
    name: "OrderEase",
    slug: "orderease",
    description: "نظام طلب سهل للمطاعم - قوائم QR، طرق دفع متعددة، وإدارة الطلبات",
    founded_year: "2021",
    headquarters: "الدمام",
    employees: "20-50",
    funding: "Seed - $4M",
    website: "https://orderease.sa",
    logo_url: "https://placehold.co/80x80?text=OrderEase",
    screenshot_url: "https://placehold.co/400x300?text=OrderEase+QR",
    categories: "Restaurant Tech",
    features: "قوائم QR,طلب ذاتي,دفع متنوع,إدارة الطلبات في الوقت الحقيقي,تطبيق المطعم",
    integrations: "Foodics,Mada,STC Pay,Apple Pay",
    certifications: "PDPL Compliant",
    badges: "Saudi-owned,Contactless Ordering"
  },
  {
    name: "PharmaCare",
    slug: "pharmacare",
    description: "منصة خدمات الصيدليات - طلب الأدوية، استشارات صيدلانية، والتوصيل",
    founded_year: "2020",
    headquarters: "الرياض",
    employees: "50-100",
    funding: "Series A - $10M",
    website: "https://pharmacare.sa",
    logo_url: "https://placehold.co/80x80?text=PharmaCare",
    screenshot_url: "https://placehold.co/400x300?text=PharmaCare+Delivery",
    categories: "HealthTech",
    features: "طلب الأدوية,استشارات صيدلانية,توصيل الأدوية,إدارة الوصفات,التأمين الصحي",
    integrations: "SEHA,Mada,STC Pay,SAR",
    certifications: "Saudi FDA,PDPL,Pharmacy License",
    badges: "Saudi-owned,Pharmacy Network"
  },
  {
    name: "CargoLink",
    slug: "cargolink",
    description: "شبكة لوجستية متكاملة - ربط بين الموردين والمشترين مع إدارة الشحنات متعددة الوسائط",
    founded_year: "2019",
    headquarters: "جدة",
    employees: "100-200",
    funding: "Series A - $15M",
    website: "https://cargolink.sa",
    logo_url: "https://placehold.co/80x80?text=CargoLink",
    screenshot_url: "https://placehold.co/400x300?text=CargoLink+Network",
    categories: "Logistics",
    features: "شبكة نقل متكاملة,إدارة الشحنات متعددة,تتبع متقدم,تأمين الشحنات,حلول متعددة",
    integrations: "SADAD,Mada,SAR,Salla",
    certifications: "PDPL Compliant,Transport License",
    badges: "Saudi-owned,Intermodal Logistics"
  },
  {
    name: "CodeAcademy KSA",
    slug: "codeacademy-ksa",
    description: "أكاديمية برمجة سعودية - دورات تطوير الويب والتطبيقات باللغة العربية",
    founded_year: "2021",
    headquarters: "الرياض",
    employees: "50-100",
    funding: "Seed - $5M",
    website: "https://codeacademy.sa",
    logo_url: "https://placehold.co/80x80?text=CodeAcademy",
    screenshot_url: "https://placehold.co/400x300?text=CodeAcademy+Courses",
    categories: "EdTech",
    features: "دورات برمجة عربية,مشاريع عملية,شهادات معتمدة,مجتمع مطورين,placement assistance",
    integrations: "Mada,Zid,LinkedIn,GitHub",
    certifications: "Ministry of Communications Approved",
    badges: "Saudi-owned,Arabic Coding"
  },
  {
    name: "MenuCraft",
    slug: "menucraft",
    description: "منصة تصميم وتحديث قوائم المطاعم - تحليل سلوك العملاء وتجربة مستخدم محسنة",
    founded_year: "2022",
    headquarters: "الرياض",
    employees: "20-50",
    funding: "Seed - $3M",
    website: "https://menucraft.sa",
    logo_url: "https://placehold.co/80x80?text=MenuCraft",
    screenshot_url: "https://placehold.co/400x300?text=MenuCraft+Design",
    categories: "Restaurant Tech",
    features: "تصميم قوائم متجاوبة,تحليل سلوك العملاء,تحسين الإيرادات,محتوى متعدد الوسائط,تحليل المنافسين",
    integrations: "Foodics,Mada,STC Pay,Google Analytics",
    certifications: "PDPL Compliant",
    badges: "Saudi-owned,Menu Optimization"
  },
  {
    name: "WellnessHub",
    slug: "wellnesshub",
    description: "منصة العافية الشاملة - برامج العقل والجسم والتغذية متابعة مع مدربين متخصصين",
    founded_year: "2021",
    headquarters: "جدة",
    employees: "50-100",
    funding: "Series A - $12M",
    website: "https://wellnesshub.sa",
    logo_url: "https://placehold.co/80x80?text=WellnessHub",
    screenshot_url: "https://placehold.co/400x300?text=WellnessHub+Dashboard",
    categories: "HealthTech",
    features: "برامج العافية,مدربون متخصصون,متابعة تقدم,تغذية مخصصة,مجتمع داعم",
    integrations: "Mada,STC Pay,Apple Health,Google Fit",
    certifications: "Ministry of Health Approved,ISO27001",
    badges: "Saudi-owned,Holistic Wellness"
  },
  {
    name: "TrainTrack",
    slug: "traintrack",
    description: "نظام إدارة التدريب للمؤسسات - تخطيط، تنفيذ، تقييم، وشهادات تدريبية",
    founded_year: "2020",
    headquarters: "الدمام",
    employees: "50-100",
    funding: "Series A - $10M",
    website: "https://traintrack.sa",
    logo_url: "https://placehold.co/80x80?text=TrainTrack",
    screenshot_url: "https://placehold.co/400x300?text=TrainTrack+Dashboard",
    categories: "EdTech",
    features: "إدارة التدريب,تخطيط الدورات,تقييم الأداء,شهادات رقمية,تقارير الامتثال",
    integrations: "Mada,Zid,SAR,HR Systems",
    certifications: "Human Resources Development Fund Approved,ISO27001",
    badges: "Saudi-owned,Corporate Training"
  },
  {
    name: "ExpressShip Express",
    slug: "expressship-express",
    description: "خدمات لوجستية عاجلة للأعمال - شحنات صغيرة، مستندات، وخدمات التوصيل المخصص",
    founded_year: "2022",
    headquarters: "الرياض",
    employees: "50-100",
    funding: "Seed - $7M",
    website: "https://expressship-express.sa",
    logo_url: "https://placehold.co/80x80?text=ExpressShip+Express",
    screenshot_url: "https://placehold.co/400x300?text=ExpressShip+Express",
    categories: "Logistics",
    features: "توصيل عاجل,شحنات صغيرة,خدمات مستندات,دعم متخصص,تتبع فوري",
    integrations: "Mada,STC Pay,Salla,Zid",
    certifications: "PDPL Compliant,Courier License",
    badges: "Saudi-owned,Urgent Delivery"
  }
];

// Create CSV string for new companies
const csvLines = newCompanies.map(company => {
  return [
    `"${company.name}"`,
    `"${company.slug}"`,
    `"${company.description}"`,
    `"${company.founded_year}"`,
    `"${company.headquarters}"`,
    `"${company.employees}"`,
    `"${company.funding}"`,
    `"${company.website}"`,
    `"${company.logo_url}"`,
    `"${company.screenshot_url}"`,
    `"${company.categories}"`,
    `"${company.features}"`,
    `"${company.integrations}"`,
    `"${company.certifications}"`,
    `"${company.badges}"`
  ].join(',');
}).join('\n');

// Append to CSV
const contentToAppend = '\n' + csvLines;

try {
  fs.appendFileSync(csvPath, contentToAppend);
  console.log('Successfully appended 30 companies to CSV');

  // Count total rows
  const fileContent = fs.readFileSync(csvPath, 'utf8');
  const rows = fileContent.trim().split('\n').length;
  console.log(`Total rows in CSV: ${rows}`);

  process.exit(0);
} catch (error) {
  console.error('Error appending to CSV:', error);
  process.exit(1);
}
