// Pre-calculated report statistics
// This file is auto-generated by scripts/generate-report-stats.js
// Last updated: 2026-03-14

export const reportStats = {
  totalCompanies: 252,
  categoryCounts: [
  {
    "name": "HealthTech",
    "count": 25
  },
  {
    "name": "EdTech",
    "count": 20
  },
  {
    "name": "PropTech",
    "count": 17
  },
  {
    "name": "HR Tech",
    "count": 16
  },
  {
    "name": "E-commerce",
    "count": 16
  },
  {
    "name": "FinTech",
    "count": 13
  },
  {
    "name": "Logistics",
    "count": 12
  },
  {
    "name": "SaaS Platforms",
    "count": 12
  },
  {
    "name": "AgriTech",
    "count": 11
  },
  {
    "name": "MarTech",
    "count": 11
  }
],
  fundingStats: {
    total: 252,
    percentage: 100.0,
    byStage: {
  "Other": 44,
  "Series A": 72,
  "Series B": 38,
  "Seed": 63,
  "Bootstrap": 35
},
  },
  topLocations: [
  {
    "city": "الرياض",
    "count": 59
  },
  {
    "city": "جدة",
    "count": 33
  },
  {
    "city": "Al Khobar",
    "count": 26
  },
  {
    "city": "Jubail",
    "count": 16
  },
  {
    "city": "Taif",
    "count": 14
  }
],
  avgFounded: 2020,
  newestFounded: 2025,
};
