const { parseArticlesFromXML } = require('../lib/xml-parser.js');
const { writeFileSync, mkdirSync } = require('fs');
const { join } = require('path');

const main = async () => {
  try {
    const articles = await parseArticlesFromXML();

    if (articles.length === 0) {
      console.warn('⚠️ No articles found from XML. Using fallback empty data.');
    }

    // Generate TypeScript file with article data
    const tsContent = `// Auto-generated by build-search.js - DO NOT EDIT
export interface Article {
  title: string;
  slug: string;
  content: string;
  excerpt: string;
  date: string;
  categories: string[];
  author: string;
  readingTime: number;
}

export const articles: Article[] = ${JSON.stringify(articles, null, 2)};

export function getArticles(): Article[] {
  return articles;
}

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find(a => a.slug === slug);
}

export function getRelatedArticles(currentSlug: string, categories: string[], limit: number = 3): Article[] {
  return articles
    .filter(a => a.slug !== currentSlug)
    .filter(a => categories.some(cat => a.categories.includes(cat)))
    .slice(0, limit);
}

export function getAllCategories(): string[] {
  const cats = new Set<string>();
  for (const a of articles) {
    a.categories.forEach(c => cats.add(c));
  }
  return Array.from(cats).sort();
}
`;

    const libDir = join(__dirname, '..', 'lib');
    const publicDataDir = join(__dirname, '..', 'public', 'data');

    writeFileSync(join(libDir, 'generated-articles.ts'), tsContent);
    mkdirSync(publicDataDir, { recursive: true });
    writeFileSync(join(publicDataDir, 'search-index.json'), JSON.stringify(articles, null, 2));

    console.log(`✅ Generated ${articles.length} articles in lib/generated-articles.ts`);
    console.log(`✅ Generated search index in public/data/search-index.json`);
  } catch (error) {
    console.error('❌ Build script failed:', error);
    process.exit(1);
  }
};

main();
